
export const apartments = [
  { unit: 101, floor: 'First', bedrooms: 1, bathrooms: 1, size: 47, price: '1,600,000', status: 'Available', color: 'green', image: '/images/units/unit-101.jpg' },
  { unit: 102, floor: 'First', bedrooms: 2, bathrooms: 1, size: 67, price: '2,100,000', status: 'Available', color: 'blue', image: '/images/units/unit-102.jpg' },
  { unit: 103, floor: 'First', bedrooms: 1, bathrooms: 1, size: 45, price: 'SOLD', status: 'Sold', color: 'yellow', image: '/images/units/unit-103.jpg' },
  { unit: 104, floor: 'First', bedrooms: 1, bathrooms: 1, size: 48, price: 'under offer', status: 'Under Offer', color: 'red', image: '/images/units/unit-104.jpg' },
  { unit: 105, floor: 'First', bedrooms: 1, bathrooms: 1, size: 48, price: '1,600,000', status: 'Available', color: 'red', image: '/images/units/unit-105.jpg' },
  { unit: 106, floor: 'First', bedrooms: 1, bathrooms: 1, size: 45, price: '1,500,000', status: 'Available', color: 'yellow', image: '/images/units/unit-106.jpg' },
  { unit: 107, floor: 'First', bedrooms: 2, bathrooms: 1, size: 67, price: '2,100,000', status: 'Available', color: 'blue', image: '/images/units/unit-107.jpg' },
  { unit: 108, floor: 'First', bedrooms: 1, bathrooms: 1, size: 47, price: '1,600,000', status: 'Available', color: 'green', image: '/images/units/unit-108.jpg' },
  { unit: 201, floor: 'Second', bedrooms: 1, bathrooms: 1, size: 47, price: '1,600,000', status: 'Available', color: 'green', image: '/images/units/unit-201.jpg' },
  { unit: 202, floor: 'Second', bedrooms: 2, bathrooms: 1, size: 68, price: '2,100,000', status: 'Available', color: 'blue', image: '/images/units/unit-202.jpg' },
  { unit: 203, floor: 'Second', bedrooms: 1, bathrooms: 1, size: 45, price: '1,500,000', status: 'Available', color: 'yellow', image: '/images/units/unit-203.jpg' },
  { unit: 204, floor: 'Second', bedrooms: 1, bathrooms: 1, size: 48, price: '1,600,000', status: 'Available', color: 'red', image: '/images/units/unit-204.jpg' },
  { unit: 205, floor: 'Second', bedrooms: 1, bathrooms: 1, size: 48, price: '1,600,000', status: 'Available', color: 'red', image: '/images/units/unit-205.jpg' },
  { unit: 206, floor: 'Second', bedrooms: 1, bathrooms: 1, size: 45, price: '1,500,000', status: 'Available', color: 'yellow', image: '/images/units/unit-206.jpg' },
  { unit: 207, floor: 'Second', bedrooms: 2, bathrooms: 1, size: 67, price: '2,100,000', status: 'Available', color: 'blue', image: '/images/units/unit-207.jpg' },
  { unit: 208, floor: 'Second', bedrooms: 1, bathrooms: 1, size: 47, price: '1,600,000', status: 'Available', color: 'green', image: '/images/units/unit-208.jpg' },
  { unit: 301, floor: 'Third', bedrooms: 2, bathrooms: 1, size: 67, price: 'SOLD', status: 'Sold', color: 'purple', image: '/images/units/unit-301.jpg' },
  { unit: 302, floor: 'Third+Loft', bedrooms: 2, bathrooms: 2, size: 77, price: '2,600,000', status: 'Available', color: 'purple', image: '/images/units/unit-302.jpg' },
  { unit: 303, floor: 'Third+Loft', bedrooms: 2, bathrooms: 2, size: 77, price: '2,600,000', status: 'Available', color: 'purple', image: '/images/units/unit-303.jpg' },
  { unit: 304, floor: 'Third+Loft', bedrooms: 2, bathrooms: 2, size: 77, price: '2,600,000', status: 'Available', color: 'purple', image: '/images/units/unit-304.jpg' },
  { unit: 305, floor: 'Third+Loft', bedrooms: 2, bathrooms: 2, size: 77, price: '2,600,000', status: 'Available', color: 'purple', image: '/images/units/unit-305.jpg' },
  { unit: 306, floor: 'Third', bedrooms: 2, bathrooms: 1, size: 67, price: '2,200,000', status: 'Available', color: 'purple', image: '/images/units/unit-306.jpg' },
];
